default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "hangframing") %>
  host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DATABASE_PORT", "11000") %>

development:
  <<: *default
  database: hangframing_ecommerce_development

test:
  <<: *default
  database: hangframing_ecommerce_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>

